add additional gh actions logging

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -25,7 +25,7 @@ jobs:
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{secrets.AWS_REGION}}
+          aws-region: ${{ secrets.AWS_REGION }}
 
       - name: Upload to S3
         run: aws s3 cp ./social-media-app.zip s3://portfolio-projects-zipped-code/social-media-app.zip
@@ -35,6 +35,9 @@ jobs:
           if ! aws elasticbeanstalk describe-applications --application-names "social-media-app"; then
             echo "Creating application social-media-app..."
             aws elasticbeanstalk create-application --application-name "social-media-app"
+            sleep 5 # Optional wait to ensure creation
+            # Verify application creation
+            aws elasticbeanstalk describe-applications --application-names "social-media-app" || echo "Failed to create application."
           else
             echo "Application social-media-app already exists."
           fi
@@ -50,7 +53,10 @@ jobs:
           aws elasticbeanstalk create-application-version \
             --application-name "social-media-app" \
             --version-label "v-${{ github.sha }}" \
-            --source-bundle S3Bucket="portfolio-projects-zipped-code",S3Key="social-media-app.zip"
+            --source-bundle S3Bucket="portfolio-projects-zipped-code",S3Key="social-media-app.zip" || echo "Failed to create application version."
+
+          # Confirm application version creation
+          aws elasticbeanstalk describe-application-versions --application-name "social-media-app" || echo "No versions found for application."
 
           aws elasticbeanstalk update-environment \
             --application-name "social-media-app" \
